
# NOTE:
# For every ORDER_SUBMITTED event,
# there MUST be exactly one terminal event:
# either ORDER_FILLED, ORDER_REJECTED, or ENGINE_REJECTED.

MARKET_SNAPSHOT = "MARKET_SNAPSHOT"

SIGNAL_EMITTED = "SIGNAL_EMITTED"
EXIT_SIGNAL_EMITTED = "EXIT_SIGNAL_EMITTED"

HUMAN_APPROVED = "HUMAN_APPROVED"

GUARD_CHECKED = "GUARD_CHECKED"
GUARD_BLOCKED = "GUARD_BLOCKED"

ORDER_SUBMITTED = "ORDER_SUBMITTED"
ORDER_FILLED = "ORDER_FILLED"
ORDER_PARTIAL_FILL = "ORDER_PARTIAL_FILL"
ORDER_REJECTED = "ORDER_REJECTED"
ENGINE_REJECTED = "ENGINE_REJECTED"

# New: Post-Trade Analysis
POST_TRADE_VALIDATION = "POST_TRADE_VALIDATION"

POSITION_UPDATED = "POSITION_UPDATED"

DAILY_REPORT = "DAILY_REPORT"
SYSTEM_STATUS = "SYSTEM_STATUS"
STRATEGY_UPDATED = "STRATEGY_UPDATED"
NEWS_UPDATE = "NEWS_UPDATE"
